### ISSUE TITLE
build.sh references build script outside of this repository

### ISSUE THREAD

**Issue by BigTuna94** [smr-llc/wooten#1]
`~/Bela/scripts/build_project.sh `  desn't seem to be in this project, or the default Bela image. It would also be nice if the build script referenced this directory as `pwd` or something less specific that the home directory `~/wooten`

**Comment by hello-adam** [comment]
it should be in the default bela image. When I put a bela image SD in a fresh bbb it doesn't actually boot until I do this:
```
ssh debian@bbb
password temppwd

sudo dd if=/dev/zero of=/dev/mmcblk1 bs=1024k count=50
sudo dd if=/dev/zero of=/dev/mmcblk1p1 bs=1024k count=50
sudo dd if=/dev/zero of=/dev/mmcblk0 bs=1024k count=50
sudo dd if=/dev/zero of=/dev/mmcblk0p1 bs=1024k count=50
```

**Comment by hello-adam** [comment]
As for the brittleness of it all - it's still very prototype-y and hacky. I think what I really need is to make my own image for flashing SDs so that the static directories are OK (just a part of this very static environment) and there's basically zero setup for non-techy people.

**Comment by BigTuna94** [comment]
Ah, I see now. The actual Bela environment is VERY static to begin with.
